# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

image:
  name: docker/compose:1.24.1
  entrypoint: ['']

stages:
  - build
  - test
  - deploy

services:
  - docker:19.03.5-dind

cache:
  key: ${CI_COMMIT_REF_SLUG}

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DATABASE_URL: postgres://postgres@postgres:5432/postgres
  SECRET_KEY: ${SECRET_KEY}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
  HEROKU_APP_NAME: ${HEROKU_APP_NAME}
  HEROKU_API_KEY: ${HEROKU_API_KEY}

.docker_config:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com

build:
  extends: .docker_config
  stage: build
  artifacts:
    paths:
      - assets
  script:
    - docker-compose -f deploy.yml build
    - docker-compose -f deploy.yml push
    - docker-compose -f deploy.yml run webpack yarn build
  only:
    - release

test_django:
  extends: .docker_config
  stage: test
  script:
    - docker-compose -f deploy.yml pull
    - docker-compose -f deploy.yml run -e DJANGO_CONFIGURATION=Testing -e DJANGO_SECRET_KEY=${SECRET_KEY} django ./manage.py validate_templates
    - docker-compose -f deploy.yml run -e DJANGO_SECRET_KEY=${SECRET_KEY} django pytest
  only:
    - release

deploy_assets:
  extends: .docker_config
  stage: deploy
  retry: 1
  dependencies:
    - build
  script:
    - docker-compose -f deploy.yml pull
    - docker-compose -f deploy.yml run -e DJANGO_CONFIGURATION=Deployment -e DATABASE_URL=${DATABASE_URL} -e DJANGO_SECRET_KEY=${SECRET_KEY} -e DJANGO_AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} -e DJANGO_AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} -e DJANGO_AWS_STORAGE_BUCKET_NAME=${AWS_BUCKET_NAME} django ./manage.py collectstatic --noinput
  only:
    - release

deploy_heroku:
  image: tmaier/dpl:latest
  stage: deploy
  dependencies:
    - build
  script:
    - dpl --provider=heroku --app=${HEROKU_APP_NAME} --api-key=${HEROKU_API_KEY} --skip-cleanup
  only:
    - release
