# Copyright (c) 2020 by Dan Jacob
# SPDX-License-Identifier: AGPL-3.0-or-later

version: '3.4'

x-env: &default-env
  DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
  REDIS_URL: redis://redis:6379/0
  DJANGO_EMAIL_HOST: mailhog
  DJANGO_EMAIL_PORT: 1025
  # These keys are for development only! Do not copy into a production environment.
  DJANGO_SECRET_KEY: seekrit
  DJANGO_VAPID_PUBLIC_KEY: BJDR4XCoFCYRmCIGcf_1fSCX4CQKFaBzruaoRhhPgVi23MLrxVkeBsgA-WYZdffCesA7DmAfy-gPHHysG3I8R-c
  DJANGO_VAPID_PRIVATE_KEY: vZH9Nz6KMSo8L8ksJFgJyK3vXfU9vIaxZcAcxavKEAk
  DJANGO_VAPID_ADMIN_EMAIL: admin@example.com

volumes:
  pg_data: {}

services:
  postgres:
    image: postgres:11.7
    environment:
      # for development only!
      - POSTGRES_PASSWORD=password
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:5.0.7
    restart: always

  mailhog:
    image: mailhog/mailhog:v1.0.0
    restart: always
    ports:
      - '8025:8025'

  webpack:
    build:
      context: .
      dockerfile: Dockerfile.webpack
    command: yarn run dev
    volumes:
      - .:/app
      - /app/node_modules

  django: &django
    build:
      context: .
      dockerfile: Dockerfile.local
    env_file: .env
    restart: on-failure
    environment: *default-env
    depends_on:
      - postgres
      - mailhog
      - redis
    volumes:
      - .:/app
    ports:
      - '80:8000'
    command: /start-django

  celeryworker:
    <<: *django
    depends_on:
      - postgres
      - mailhog
      - redis
    ports: []
    command: /start-celeryworker
